spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket-main-db
    username: ticketmain
    password: ticketmain
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080